sonar.projectKey=GeovaniaLuiza_agora-tech-park-fullstack
sonar.organization=geovanialuiza
sonar.projectName=Agora Tech Park Fullstack
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.test.js,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,backend/src/server.js,frontend/src/main.jsx
sonar.coverage.exclusions=backend/src/server.js,frontend/src/main.jsx
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
