import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import formRoutes from './routes/formRoutes.js';
import authRoutes from './routes/authRoutes.js';
import responseRoutes from './routes/responseRoutes.js';
import indicatorRoutes from './routes/indicatorRoutes.js';
import organizationRoutes from './routes/organizationRoutes.js';
import accessRoutes from './routes/accessRoutes.js';
import { errorHandler } from './middlewares/errorHandler.js';
import { configureTrustProxy, createRateLimiter, RATE_LIMIT_CONFIG } from './middlewares/rateLimits.js';
const app = express();
app.disable('x-powered-by');
configureTrustProxy(app);
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5174', methods:['GET','POST','PUT','PATCH','DELETE'], allowedHeaders:['Content-Type','Authorization'] }));
app.use(createRateLimiter(RATE_LIMIT_CONFIG.global));
app.use(express.json({ limit:'100kb' }));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', authRoutes);
app.use('/api/forms', formRoutes);
app.use('/api', responseRoutes);
app.use('/api/indicators', indicatorRoutes);
app.use('/api/organizations', organizationRoutes);
app.use('/api/admin', accessRoutes);
app.use(errorHandler);
export default app;
