import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import formRoutes from './routes/formRoutes.js';
import authRoutes from './routes/authRoutes.js';
import responseRoutes from './routes/responseRoutes.js';
import indicatorRoutes from './routes/indicatorRoutes.js';
import organizationRoutes from './routes/organizationRoutes.js';
import accessRoutes from './routes/accessRoutes.js';
import notificationRoutes from './routes/notificationRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import spreadsheetImportRoutes from './routes/spreadsheetImportRoutes.js';
import healthRoutes from './routes/healthRoutes.js';
import indicatorManagementRoutes from './routes/indicatorManagementRoutes.js';
import indicatorImportRoutes from './routes/indicatorImportRoutes.js';
import { errorHandler } from './middlewares/errorHandler.js';
import { configureTrustProxy, createRateLimiter, RATE_LIMIT_CONFIG } from './middlewares/rateLimits.js';
import { requestLogger } from './middlewares/requestLogger.js';
import { metricsHandler, metricsMiddleware } from './observability/metrics.js';
const app = express();
app.disable('x-powered-by');
configureTrustProxy(app);
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5174', methods:['GET','POST','PUT','PATCH','DELETE'], allowedHeaders:['Content-Type','Authorization'] }));
app.use(requestLogger);
app.use(metricsMiddleware);
app.get('/metrics', metricsHandler);
app.use(createRateLimiter(RATE_LIMIT_CONFIG.global));
app.use('/api/auth/me/avatar', express.json({ limit: '3mb' }));
app.use(express.json({ limit:'100kb' }));
app.use('/api/health', healthRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/forms', formRoutes);
app.use('/api', responseRoutes);
app.use('/api/indicators', indicatorRoutes);
app.use('/api/indicator-management', indicatorManagementRoutes);
app.use('/api/indicator-imports', indicatorImportRoutes);
app.use('/api/organizations', organizationRoutes);
app.use('/api/admin', accessRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/admin/spreadsheet-imports', spreadsheetImportRoutes);
app.use(errorHandler);
export default app;
