import { Router } from 'express';
import * as controller from '../controllers/accessController.js';
import { authenticate, authorize } from '../middlewares/auth.js';
const router = Router();
router.use(authenticate, authorize('ADMIN'));
router.get('/access-requests', controller.list);
router.get('/users', controller.users);
router.get('/audit', controller.audit);
router.get('/access-requests/:id', controller.get);
router.post('/access-requests/:id/approve', controller.approve);
router.post('/access-requests/:id/reject', controller.reject);
router.patch('/users/:id/status', controller.status);
router.patch('/users/:id/role', controller.role);
router.post('/users/:id/organizations', controller.link);
router.delete('/users/:id/organizations/:organizationId', controller.unlink);
export default router;
