export const SOURCE_TYPES = Object.freeze({
  LIVE: 'LIVE',
  SPREADSHEET: 'SPREADSHEET_IMPORT',
  FORM: 'FORM_RESPONSE',
  MANUAL: 'MANUAL_ENTRY',
  SYSTEM: 'SYSTEM_CALCULATION',
});

export const INDICATOR_CATALOG = Object.freeze([
  { row: 4, code: 'NOVAS_STARTUPS', name: 'Nº de Novas Startups', category: 'Empresas e ecossistema', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 6, code: 'STARTUPS_ATIVAS', name: 'Nº de Startups Ativas', category: 'Empresas e ecossistema', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 14, code: 'NOVAS_EMPRESAS_ATIVAS', name: 'Nº Total de Novas Empresas Ativas', category: 'Empresas e ecossistema', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 15, code: 'EMPRESAS_ATIVAS_TOTAL', name: 'Nº Total de Empresas Ativas', category: 'Empresas e ecossistema', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 17, code: 'FATURAMENTO_EMPRESAS', name: 'Faturamento das Empresas Atendidas', category: 'Empresas e ecossistema', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 19, code: 'ARRECADACAO_EMPRESAS', name: 'Arrecadação Total das Empresas Atendidas', category: 'Empresas e ecossistema', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 21, code: 'COLABORADORES_EMPRESAS', name: 'Nº Total de Colaboradores das Empresas Atendidas', category: 'Empresas e ecossistema', unit: 'PESSOA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 24, code: 'RECEITA_TOTAL_CENTRO', name: 'Receita Total do Centro', category: 'Saúde financeira', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 25, code: 'DESPESAS_TOTAL_CENTRO', name: 'Custos e Despesas Totais do Centro', category: 'Saúde financeira', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 26, code: 'RESULTADO_ANUAL_CENTRO', name: 'Resultado do Centro', category: 'Saúde financeira', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'CALCULATED' },
  { row: 28, code: 'DESPESAS_CUSTEADAS_RECEITA_PROPRIA', name: '% de Despesas Custeadas com Receitas Próprias', category: 'Saúde financeira', unit: 'PERCENT', valueType: 'PERCENT', aggregation: 'AVERAGE' },
  { row: 30, code: 'EQUIPE_CENTRO', name: 'Nº de Pessoas na Equipe do Centro de Inovação', category: 'Gestão', unit: 'PESSOA', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 32, code: 'OCUPACAO_PREDIO', name: 'Ocupação do Prédio', category: 'Gestão', unit: 'PERCENT', valueType: 'PERCENT', aggregation: 'AVERAGE' },
  { row: 35, code: 'PROJETOS_SUBMETIDOS', name: 'Nº de Projetos Submetidos para Editais', category: 'Projetos e captação', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 36, code: 'PROJETOS_GANHOS', name: 'Nº de Projetos Ganhos em Editais', category: 'Projetos e captação', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 37, code: 'VALOR_PROJETOS_GANHOS', name: 'Valor de Projetos Ganhos em Editais', category: 'Projetos e captação', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 40, code: 'VISITANTES_CENTRO', name: 'Nº de Visitantes no Centro', category: 'Impacto e engajamento', unit: 'PESSOA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 43, code: 'VALOR_PROJETOS_CAPACITACAO', name: 'Valor de Projetos de Capacitação de Empresas', category: 'Capacitações', unit: 'BRL', valueType: 'CURRENCY', aggregation: 'SUM' },
  { row: 45, code: 'CAPACITACOES_REALIZADAS', name: 'Nº de Capacitações Realizadas', category: 'Capacitações', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 47, code: 'EMPRESAS_CAPACITADAS', name: 'Nº de Empresas Capacitadas', category: 'Capacitações', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 49, code: 'PESSOAS_CAPACITADAS', name: 'Nº de Pessoas Capacitadas', category: 'Capacitações', unit: 'PESSOA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 54, code: 'FUNCOES_ATIVAS', name: 'Nº de Funções Ativas', category: 'Funções e programas', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'COUNT' },
  { row: 64, code: 'PROGRAMAS_INICIADOS', name: 'Nº de Programas Iniciados', category: 'Funções e programas', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 87, code: 'EVENTOS_REALIZADOS', name: 'Nº de Eventos Realizados', category: 'Impacto e engajamento', unit: 'UNIDADE', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 1370, code: 'MANTENEDORES', name: 'Nº de Mantenedores', category: 'Ecossistema', unit: 'ORGANIZAÇÃO', valueType: 'NUMBER', aggregation: 'COUNT', annualColumn: 2 },
  { row: 1386, code: 'IES_REGIAO', name: 'Nº de Instituições de Ensino Superior na Região', category: 'Ecossistema', unit: 'ORGANIZAÇÃO', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 1387, code: 'IES_ATENDIDAS', name: 'Nº de Instituições de Ensino Superior Atendidas', category: 'Ecossistema', unit: 'ORGANIZAÇÃO', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 1400, code: 'MUNICIPIOS_REGIAO', name: 'Nº de Municípios na Região', category: 'Ecossistema', unit: 'MUNICÍPIO', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 1401, code: 'MUNICIPIOS_ATENDIDOS', name: 'Nº de Municípios Atendidos', category: 'Ecossistema', unit: 'MUNICÍPIO', valueType: 'NUMBER', aggregation: 'LAST_VALUE' },
  { row: 1413, code: 'ENTIDADES_REGIAO', name: 'Nº de Entidades na Região', category: 'Ecossistema', unit: 'ORGANIZAÇÃO', valueType: 'NUMBER', aggregation: 'LAST_VALUE', annualColumn: 2 },
  { row: 1414, code: 'ENTIDADES_ATENDIDAS', name: 'Nº de Entidades Atendidas', category: 'Ecossistema', unit: 'ORGANIZAÇÃO', valueType: 'NUMBER', aggregation: 'LAST_VALUE', annualColumn: 2 },
  { row: 1431, code: 'GRANDES_EMPRESAS_REGIAO', name: 'Nº de Grandes Empresas na Região', category: 'Ecossistema', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'LAST_VALUE', annualColumn: 2 },
  { row: 1432, code: 'GRANDES_EMPRESAS_ATENDIDAS', name: 'Nº de Grandes Empresas Atendidas', category: 'Ecossistema', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'LAST_VALUE', annualColumn: 2 },
  { row: 1447, code: 'EMPRESAS_PRE_INCUBADAS', name: 'Nº de Empresas Pré-Incubadas', category: 'Empreendedorismo', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 1480, code: 'EMPRESAS_INCUBADAS', name: 'Nº de Empresas Incubadas', category: 'Empreendedorismo', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'COUNT', annualColumn: 2 },
  { row: 1512, code: 'EMPRESAS_ACELERADAS', name: 'Nº de Empresas Aceleradas', category: 'Empreendedorismo', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'COUNT', annualColumn: 2 },
  { row: 1516, code: 'EMPRESAS_RESIDENTES', name: 'Nº de Empresas Residentes', category: 'Empresas e ecossistema', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'SUM' },
  { row: 1601, code: 'GRANDES_EMPRESAS_APOIADAS', name: 'Nº de Grandes Empresas Apoiadas', category: 'Inovação aberta', unit: 'EMPRESA', valueType: 'NUMBER', aggregation: 'COUNT', annualColumn: 2 },
  { row: 1616, code: 'FASE_CENTRO', name: 'Fase do Centro', category: 'Diagnóstico', unit: 'TEXTO', valueType: 'TEXT', aggregation: 'MANUAL', annualColumn: 2 },
  { row: 1617, code: 'INSTALACOES_CENTRO', name: 'Prédio / Instalações físicas', category: 'Diagnóstico', unit: 'TEXTO', valueType: 'TEXT', aggregation: 'MANUAL', annualColumn: 2 },
  { row: 1618, code: 'LEI_INOVACAO_EXISTENTE', name: 'Lei de Inovação', category: 'Diagnóstico', unit: 'TEXTO', valueType: 'TEXT', aggregation: 'MANUAL', annualColumn: 2 },
]);

export const DASHBOARD_CODES = Object.freeze([
  'EMPRESAS_ATIVAS_TOTAL', 'NOVAS_EMPRESAS_ATIVAS', 'STARTUPS_ATIVAS',
  'COLABORADORES_EMPRESAS', 'OCUPACAO_PREDIO', 'PROJETOS_SUBMETIDOS',
  'PROJETOS_GANHOS', 'VALOR_PROJETOS_GANHOS', 'VISITANTES_CENTRO',
  'RECEITA_TOTAL_CENTRO', 'DESPESAS_TOTAL_CENTRO', 'RESULTADO_ANUAL_CENTRO',
  'CAPACITACOES_REALIZADAS', 'EMPRESAS_CAPACITADAS', 'PESSOAS_CAPACITADAS',
  'PROGRAMAS_INICIADOS', 'FUNCOES_ATIVAS', 'FATURAMENTO_EMPRESAS',
]);

export const REFERENCE_TOTALS_2025 = Object.freeze({
  EMPRESAS_ATIVAS_TOTAL: 81,
  NOVAS_EMPRESAS_ATIVAS: 43,
  STARTUPS_ATIVAS: 12,
  COLABORADORES_EMPRESAS: 1054,
  OCUPACAO_PREDIO: 0.95,
  PROJETOS_SUBMETIDOS: 11,
  PROJETOS_GANHOS: 3,
  VALOR_PROJETOS_GANHOS: 970000,
  VISITANTES_CENTRO: 2649,
  RECEITA_TOTAL_CENTRO: 1829191,
  DESPESAS_TOTAL_CENTRO: 1394111,
  RESULTADO_ANUAL_CENTRO: 435080,
  CAPACITACOES_REALIZADAS: 88,
  EMPRESAS_CAPACITADAS: 2144,
  PESSOAS_CAPACITADAS: 12730,
  PROGRAMAS_INICIADOS: 19,
  FUNCOES_ATIVAS: 7,
});

// A planilha 2026 é o novo modelo de coleta e não possui totais históricos fixos.
export const REFERENCE_TOTALS_2026 = Object.freeze({});
